spring:
  datasource:
    url: jdbc:postgresql://minikube:31000/db
    username: user
    password: password


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistcs: true
    hibernate:
      ddl-auto: update