spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db-postgres
    username: db-postgres
    password: asdf1234
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistcs: true
    hibernate:
      ddl-auto: update